#!/bin/sh

mkdir /tmp/font-install && cd /tmp/font-install
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip"
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraMono.zip"
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip"
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Iosevka.zip"
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip"
unzip '*.zip'
rm -rf *.zip
mkdir $HOME/.fonts || true
mv /tmp/font-install/* $HOME/.fonts
rm -rf /tmp/font-install
