#!/bin/bash
KITTY_PATH_LINUX=$HOME/.local/kitty.app
KITTY_PATH_MAC=/Applications/kitty.app
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
if [ -d $KITTY_PATH_LINUX ]; then
    KITTY_PATH=$KITTY_PATH_LINUX
else
    KITTY_PATH=$KITTY_PATH_MAC
fi


# Create a symbolic link to add kitty to PATH (assuming ~/.local/bin is in
# your PATH)
sudo ln -s $KITTY_PATH/bin/kitty /usr/local/bin
# Place the kitty.desktop file somewhere it can be found by the OS
cp $KITTY_PATH/share/applications/kitty.desktop ~/.local/share/applications/
# If you want to open text files and images in kitty via your file manager also add the kitty-open.desktop file
cp $KITTY_PATH/share/applications/kitty-open.desktop ~/.local/share/applications/
# Update the path to the kitty icon in the kitty.desktop file(s)
sed -i "s|Icon=kitty|Icon=$KITTY_PATH/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
